### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Prophet1984** [dani69654/Script_GenerateMnem_Check_Balance#14]

**Comment by al3xcjc** [comment]
Hello again, i have managed to resolve the first error but now I get this:


C:\Users\Administrator\Documents\CRYPTO\evm_scan_wallets-main>npm start

> script_generatemnem_check_balance@1.0.0 start
> node index.js

No Sendgrid API key found. This function is disabled.
▰▰▰▰▱▱▱ Scanning blockchainC:\Users\Administrator\Documents\CRYPTO\evm_scan_wallets-main\index.js:34
    throw new Error(error.message || error)
          ^

Error: Unexpected error occurred
    at scan (C:\Users\Administrator\Documents\CRYPTO\evm_scan_wallets-main\index.js:34:11)






![1](https://user-images.githubusercontent.com/115896258/196006232-0787f672-1ef7-45ba-a5ce-747be12b3bc2.jpg)

**Comment by al3xcjc** [comment]
i think i figured it out. plase take a look, does this mean it works?
![1](https://user-images.githubusercontent.com/115896258/196006850-9daf1012-956d-40fe-9a88-933ebc0630da.jpg)

**Comment by al3xcjc** [comment]
i got this after a while.... what can it be?
![1](https://user-images.githubusercontent.com/115896258/196007814-c61f023a-25fa-4618-8174-03c6eeb60de2.jpg)
